import datetime
import logging
from typing import Any

from app.core.config import settings
from app.infrastructure.aries.chroma_client import chroma_manager
from app.infrastructure.aries.mongo_client import aries_mongo
from app.infrastructure.aries.redis_client import aries_redis
from app.services.aries.pipeline.brain import brain_adapter

logger = logging.getLogger(__name__)


class MemoryService:
    """Unified coordinator for the Aries agent's multi-tier memory architecture.

    MemoryService provides a high-level API for interacting with the different
    layers of cognitive storage:
    1. Sensory/Short-term Memory (Redis): Immediate context and editor state.
    2. Semantic Memory (ChromaDB): Vector-based RAG for facts and logic.
    3. Episodic Memory (MongoDB): Long-term conversation and activity logs.

    This service ensures that all memory updates are synchronized across the
    appropriate tiers based on their TTL and retrieval requirements.
    """

    async def record_user_fact(self, username: str, concept: str, value: str) -> None:
        """Persists a personality fact in the 'Memory Palace' (ChromaDB).

        Args:
            username (str): The name of the user.
            concept (str): The categorized concept (e.g., 'coding_preference').
            value (str): The raw text fact retrieved from conversation.
        """
        fact_id = f"user_fact:{username}:{concept}"
        metadata = {
            "username": username,
            "concept": concept,
            "skill_id": "user-personality",
            "type": "fact",
        }

        await chroma_manager.add_fact(
            collection_name="user_memory",
            content=value,
            metadata=metadata,
            fact_id=fact_id,
        )
        logger.info(f"MEMORY: Recorded fact for '{username}' in ChromaDB: {concept}")

    async def summarize_and_store_problem(
        self, slug: str, title: str, description: str
    ) -> None:
        """Summarizes a problem and indexes it for semantic retrieval.

        This background task ensures that Aries has a high-level 'understanding'
        of new problems before they are even loaded into the main context.

        Args:
            slug (str): Problem slug identifier.
            title (str): Problem title.
            description (str): Raw HTML or text description.
        """
        system_prompt = (
            "You are a DSA expert. Summarize the following coding problem "
            "into 2-3 concise sentences. Focus on the core objective and constraints."
        )
        user_msg = f"Problem: {title}\n\n{description}"

        # 1. Summarization with Configured Brain
        summary = await brain_adapter.generate_response(
            user_msg,
            system_prompt,
            provider=settings.BRAIN_PROVIDER,
            model=settings.BRAIN_MODEL,
        )

        # 2. Store in Semantic Memory
        await chroma_manager.add_fact(
            collection_name="problem_summaries",
            content=summary,
            metadata={"slug": slug, "title": title, "type": "problem_summary"},
            fact_id=f"problem_summary:{slug}",
        )
        logger.info(f"MEMORY: Summarized and indexed problem '{slug}' in ChromaDB.")

    async def record_interaction(
        self, session_id: str, username: str, user_msg: str, ai_msg: str, skill_id: str
    ) -> None:
        """Records a single conversation turn across all appropriate memory tiers.

        Args:
            session_id (str): The unique session identifier.
            username (str): The name of the user.
            user_msg (str): Transcription of what the user said.
            ai_msg (str): The text response generated by the AI.
            skill_id (str): The active Aries skill persona.
        """
        # 1. Short-term (Redis): Update the rolling conversation window.
        from app.services.aries.pipeline.history import AriesHistoryManager

        await AriesHistoryManager.add_interaction(session_id, user_msg, ai_msg)

        # 2. Episodic (MongoDB): Archive the interaction for long-term review.
        await aries_mongo.save_episode(
            session_id=session_id,
            user_id=username,
            interactions=[
                {
                    "role": "user",
                    "content": user_msg,
                    "timestamp": datetime.datetime.utcnow().isoformat(),
                },
                {
                    "role": "aries",
                    "content": ai_msg,
                    "timestamp": datetime.datetime.utcnow().isoformat(),
                },
            ],
            summary=f"Turn in {skill_id}",
        )

    async def record_event(
        self, session_id: str, username: str, event_type: str, details: dict[str, Any]
    ) -> None:
        """Captures a system or user-triggered UI event in episodic memory.

        Args:
            session_id (str): The unique session identifier.
            username (str): The name of the user.
            event_type (str): The event name (e.g., 'LOAD_PROBLEM').
            details (Dict[str, Any]): Structured metadata about the event.
        """
        await aries_mongo.save_episode(
            session_id=session_id,
            user_id=username,
            interactions=[
                {
                    "role": "system",
                    "event": event_type,
                    "details": details,
                    "timestamp": datetime.datetime.utcnow().isoformat(),
                }
            ],
            summary=f"Event: {event_type}",
        )

    async def set_current_code(self, session_id: str, code: str) -> None:
        """Updates the agent's immediate sensory perception of the code editor.

        Args:
            session_id (str): The unique session identifier.
            code (str): The raw source code from the editor.
        """
        await aries_redis.set_current_code(session_id, code)

    async def set_current_problem(
        self, session_id: str, problem_data: dict[str, Any]
    ) -> None:
        """Updates the sensory perception of the currently active LeetCode problem.

        Args:
            session_id (str): The unique session identifier.
            problem_data (Dict[str, Any]): Problem metadata dictionary.
        """
        await aries_redis.set_current_problem(session_id, problem_data)

    async def record_code_activity(
        self,
        session_id: str,
        username: str,
        code: str,
        activity_type: str,
        results: Any,
        status: str,
    ) -> None:
        """Synchronizes a code execution event across sensory and episodic tiers.

        Args:
            session_id (str): The session identifier.
            username (str): The username.
            code (str): The source code actually executed.
            activity_type (str): 'RUN' or 'SUBMIT'.
            results (Any): The output or test case results.
            status (str): Success or failure label.
        """
        # 1. Update Sensory (Redis): The executed code is now the 'active' code.
        await aries_redis.set_current_code(session_id, code)

        # 2. Archive Episodic (MongoDB): Record the detailed result objectively.
        session_data = {
            "session_id": session_id,
            "username": username,
            "code": code,
            "type": activity_type,
            "results": results,
            "status": status,
        }
        await aries_mongo.save_code_session(session_data)

    async def get_lightweight_context(self, session_id: str) -> dict[str, Any]:
        """Fetches high-speed, hot context from Redis sensory memory only.

        Args:
            session_id (str): The unique session identifier.

        Returns:
            Dict[str, Any]: History and Problem metadata.
        """
        history = await aries_redis.get_context(session_id)
        current_problem = await aries_redis.get_current_problem(session_id)
        return {
            "history": history,
            "current_problem": current_problem,
        }

    async def get_full_context(
        self,
        session_id: str,
        username: str,
        query: str = "",
        skill_id: str = "aries-default",
    ) -> dict[str, Any]:
        """Assembles the complete cognitive context for the reasoning engine.

        This method performs a cross-tier retrieval to build a unified 'mind'
        for the agent. It includes:
        - Redis: Conversation history and editor state.
        - MongoDB: Recent code results and system events.
        - ChromaDB: Semantic user facts and problem summaries.

        Args:
            session_id (str): The unique session ID.
            username (str): The user's name.
            query (str): The user's latest query (used for semantic RAG).
            skill_id (str): The active skill persona.

        Returns:
            Dict[str, Any]: A rich dictionary containing all retrieval results.
        """
        # 1. RETRIEVE HOT CONTEXT (Sensory)
        history = await aries_redis.get_context(session_id)
        current_code = await aries_redis.get_current_code(session_id)
        current_problem = await aries_redis.get_current_problem(session_id)

        # 2. RETRIEVE EPISODIC CONTEXT (Logs)
        code_results = await aries_mongo.get_recent_code_sessions(
            username, session_id, limit=2
        )
        episodes = await aries_mongo.get_recent_episodes(username, limit=3)

        # 3. RETRIEVE SEMANTIC CONTEXT (Memory Palace)
        user_facts = []
        semantic_hits = []
        if query:
            user_facts = await chroma_manager.similarity_search(
                collection_name="user_memory",
                query=query,
                limit=5,
                filter={"username": username},
            )
            semantic_hits = await chroma_manager.similarity_search(
                collection_name="knowledge_base", query=query, limit=3
            )

        # 4. PROBLEM HYBRID LOGIC
        problem_summary = None
        if current_problem and current_problem.get("slug"):
            slug = current_problem["slug"]
            summaries = await chroma_manager.similarity_search(
                collection_name="problem_summaries",
                query=slug,
                limit=1,
                filter={"slug": slug},
            )
            if summaries:
                problem_summary = summaries[0]["content"]

        # 5. DYNAMIC DATA: Daily Challenge Fetch (Proactive Context)
        daily_challenge = None
        try:
            from app.api.mcp.router import daily_challenge_cache

            if daily_challenge_cache:
                daily_challenge = daily_challenge_cache.get("data")
        except Exception as e:
            logger.debug(f"MEMORY: Daily challenge cache lookup failed: {e}")

        return {
            "history": history,
            "current_code": current_code,
            "current_problem": current_problem,
            "problem_summary": problem_summary,
            "code_results": code_results,
            "semantic_knowledge": semantic_hits,
            "daily_challenge": daily_challenge,
            "episodes": episodes,
            "user_facts": user_facts,
        }


# Global instance of the MemoryService.
memory_service = MemoryService()
